version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'gomod'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
      include: 'scope'

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "11:00"
    open-pull-requests-limit: 10
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
      time: "11:00"
    open-pull-requests-limit: 10
    labels:
      - T:dependencies
