name: Test
on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"
      - name: Testing build
        run: go build
      - name: Run common tests
        run: go test -run '.' common_test.go common.go types.go
